ObsidianLabs/eth-components

- packages/eth-explorer/src/buttons/TransferButton.js
| before | after |
|-----|----|
|![image](https://user-images.githubusercontent.com/20736452/144425947-bf93aaa7-f3d1-4a9e-b2a5-a02c573267e1.png)|![image](https://user-images.githubusercontent.com/20736452/144426027-42dbc333-dd22-459a-ab13-61f5fe0dcb67.png)
> feat: make the transfer icon meaningful

- packages/eth-project/src/Project/index.js
Hide Open menu item of context menu when node type is folder
> feat: hide Open menu item

- packages/eth-network/src/networkManager.js
- packages/eth-sdk/src/BrowserExtension.js
- yarn.lock
Change metamask chainId while editor chainId changed.
Change editor chainId while metamask chainId changed.
metamask chainId 更改时同步更改编辑器 chainId
编辑器 chainId 更改时同步更改 metamask chainId
https://user-images.githubusercontent.com/6639067/148776023-c0a120e1-f333-49d3-862f-80dc14cf0dce.mov
> feat: bind network change between editor and metamask

- packages/eth-explorer/src/buttons/TransferButton.js
- packages/eth-sdk/src/utils/index.js
process fuction for address format
> feat: improve address format utils

- packages/eth-network/src/networkManager.js
- packages/eth-sdk/src/BrowserExtension.js
- packages/eth-sdk/src/EthersClient/index.js
fix explorer error after network changed
> fix:explorer error after network changed

- packages/eth-network/src/RemoteNetwork/RemoteNetworkInfo.js
- packages/eth-network/src/networkManager.js
- packages/eth-network/src/redux/index.js
- packages/eth-sdk/src/BrowserExtension.js
feat: auto-add-new-network-while-chianlist-contains-rebase
> feat: auto-add-new-network-while-chianlist-contains-rebase

- packages/eth-contract/src/AbiStorage/AbiInputModal.js
- packages/eth-contract/src/AbiStorage/AbiStorageModal.js
- packages/eth-network/src/LocalNetwork/InstanceConfigModal.js
- packages/eth-network/src/NetworkStatus/RpcClientModal.js
Related to https://github.com/ObsidianLabs/electron-components/pull/113
> Use bootstrap defined classes for modals

- packages/eth-compiler/src/CompilerButton.js
- packages/eth-project/src/Project/ProjectSettingsTab/index.js
- packages/eth-project/src/Project/ProjectToolbar/index.js
> feat: allow filetree to be readonly

- packages/eth-contract/src/components/ContractForm/index.js
> feat(ContractForm): format address rpc client.

- packages/eth-contract/src/ContractPage.js
dealing with boundary issues on windows.
> fix(ContractPage): dealing with boundary issues on windows.

- packages/eth-welcome/package.json
- packages/eth-welcome/src/Welcome.js
- packages/eth-welcome/src/index.js
- packages/eth-welcome/src/styles.scss
features:
* add a tutorial panel to the Welcome modal
code modify:
* changed the eth-welcome component 
undo:
* need to update the Chinese version of description
> feat: add tutorialbar to welcome

- packages/eth-welcome/src/Welcome.js
fix: remove useless denpendency
> fix: remove useless dependency in welcome.js

- packages/eth-contract/src/ResultContent.js
- packages/eth-header/src/Header.js
- packages/eth-header/src/headerActions.js
- packages/eth-sdk/src/utils/index.js
> fix: keypair bugs

- packages/eth-sdk/src/networks.js
the original network address cannot be connected MEATMASK
> fix: modification the chain polygontest network url

- packages/eth-network/src/networkManager.js
- yarn.lock
Co-authored-by: flowfire <ziyi.meng@obsidians.io>
> fix: support-other-browser-extension (#88)

- .github/workflows/trigger_deploy.yml
- fix: building warning
- chore(build): add trigger deploy job
> chore: add trigger deploy job

- packages/eth-sdk/package.json
- packages/eth-sdk/src/EthersClient/index.js
harmony need to replace with post request
> fix: harmony and conflux get transaction history

- packages/eth-contract/src/ContractPage.js
- packages/eth-explorer/src/AccountPage.js
> fix: tab cache loss problem

- packages/eth-project/src/Project/ProjectSettingsTab/index.js
- packages/eth-project/src/Project/ProjectToolbar/DeployButton.js
- packages/eth-project/src/Project/ProjectToolbar/ScriptsButton.js
- packages/eth-project/src/Project/ProjectToolbar/index.js
-[x] fix: hide project button while sharing
> Fix: hide button share status

- packages/eth-contract/src/components/ContractForm/ParamInput/AddressParamInput.js
- packages/eth-header/src/Header.js
-[x] fix: matamask lock account cause webpage crash
> fix: matamsk lock account cause webpage crash

- packages/eth-explorer/src/buttons/TransferButton.js
- packages/eth-sdk/src/EthersClient/index.js
> Fix: metamask transaction failed

- packages/eth-project/src/Project/ProjectToolbar/DeployButton.js
- packages/eth-project/src/Project/ProjectToolbar/index.js
- packages/eth-project/src/ProjectManager.js
> fix: update the notification of deploying shared project

- packages/eth-network/package.json
- packages/eth-network/rollup.config.js
- packages/eth-network/src/constants/extraRpcs.json
- packages/eth-network/src/networkManager.js
- packages/eth-sdk/src/BrowserExtension.js
- packages/eth-sdk/src/index.js
- packages/eth-sdk/src/utils/index.js
> Fix: update chainlist information

- packages/eth-explorer/src/AccountTransactions/Address.js
- packages/eth-explorer/src/AccountTransactions/TransactionRow.js
- packages/eth-explorer/src/AccountTransactions/index.js
- packages/eth-queue/src/TransactionDetails.js
- packages/eth-queue/src/index.js
> feat: click the transactions txHash to display the new transaction details modal

- packages/eth-sdk/src/networks.js
> feat: adjust network drop-down list UI interface
